baseURL = 'https://rpg.post-self.ink/'
languageCode = 'en-us'
title = 'The Post-Self RPG'
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2021
    customCSS = ['/css/rpg.css']
    subtitle = ''
    subtitleLink = 'https://post-self.ink'

[markup.goldmark.renderer]
    unsafe = true
